titles = {
            "Miss": "Ms",
            "Mr": "Mr",
            "Mrs": "Mrs",
            "Ms": "Ms",
            "Sir": "Mr",
            'Mme': "Mrs",
            "Master": "Academic",
            "Dr": "Academic",
            "Rev": "Royalty",
            "Col": "Royalty",
            "Major": "Royalty",
            "Lady": "Ms",
            "Don": "Mr",
            "Mlle": "Ms",
            "Capt": "Royalty",
            "the Countess": "Royalty",
            "Jonkheer": "Royalty",
        }